name: Auto Update Submodule
on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch: 

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false # Do not checkout submodules automatically

      - name: Configure Git
        run: |
          git config --global user.name "Rakshitha Kamath"
          git config --global user.email "rakshithakamath94@gmail.com"

      - name: Update submodule to latest remote version
        run: |
          git submodule update --init --recursive --remote -f
          git add test

      - name: Commit and Push changes
        run: |
          git commit -s -m 'Update submodule to latest'
          git push origin release-9.1
        with:
          token: ${{ secrets.PAT }} 
